
services:
  backend:
    build: .
    container_name: app_backend
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run dev & node src/services/jobProcessor.js"

  mongodb:
    image: mongo:6.0
    container_name: mongodb_server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodbdata:
    driver: local
