
services:
  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    command: sh -c "npm run dev & node src/services/jobProcessor.js"

  frontend:
    build: ./frontend
    container_name: app_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev 

  mongodb:
    image: mongo:6.0
    container_name: mongodb_server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodbdata:
    driver: local
